### ISSUE TITLE
failing TestFetchGraphToBlocks test

### ISSUE THREAD

**Issue by marten-seemann** [ipfs/go-fetcher#20]
```
=== RUN   TestFetchGraphToBlocks
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8049f6c]

goroutine 930 [running]:
runtime/internal/atomic.Xadd64(0xa54e59c, 0x1, 0x0, 0xa5501b0, 0x7)
	/opt/hostedtoolcache/go/1.15.12/x64/src/runtime/internal/atomic/asm_386.s:105 +0xc
github.com/ipfs/go-bitswap/testnet.(*networkClient).SendMessage(0xa54e580, 0x872a2e0, 0xa76f920, 0xa550150, 0x7, 0x872e940, 0xa76fac0, 0x0, 0xffffffff)
	/home/runner/go/pkg/mod/github.com/ipfs/go-bitswap@v0.3.3/testnet/virtual.go:216 +0x9c
github.com/ipfs/go-bitswap/testnet.(*messagePasser).SendMsg(0xa416920, 0x872a2e0, 0xa76f920, 0x872e940, 0xa76fac0, 0x2, 0x0)
	/home/runner/go/pkg/mod/github.com/ipfs/go-bitswap@v0.3.3/testnet/virtual.go:260 +0x51
github.com/ipfs/go-bitswap/internal/messagequeue.(*MessageQueue).sendMessage(0xa4f83c0)
	/home/runner/go/pkg/mod/github.com/ipfs/go-bitswap@v0.3.3/internal/messagequeue/messagequeue.go:518 +0x247
github.com/ipfs/go-bitswap/internal/messagequeue.(*MessageQueue).sendIfReady(0xa4f83c0)
	/home/runner/go/pkg/mod/github.com/ipfs/go-bitswap@v0.3.3/internal/messagequeue/messagequeue.go:487 +0x39
github.com/ipfs/go-bitswap/internal/messagequeue.(*MessageQueue).runQueue(0xa4f83c0)
	/home/runner/go/pkg/mod/github.com/ipfs/go-bitswap@v0.3.3/internal/messagequeue/messagequeue.go:436 +0x3eb
created by github.com/ipfs/go-bitswap/internal/messagequeue.(*MessageQueue).Startup
	/home/runner/go/pkg/mod/github.com/ipfs/go-bitswap@v0.3.3/internal/messagequeue/messagequeue.go:374 +0x8c
FAIL	github.com/ipfs/go-fetcher/helpers	0.020s
=== RUN   TestFetchIPLDPrimeNode
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8049f6c]

goroutine 930 [running]:
runtime/internal/atomic.Xadd64(0x8d4c41c, 0x1, 0x0, 0x8d4e130, 0x7)
	/opt/hostedtoolcache/go/1.15.12/x64/src/runtime/internal/atomic/asm_386.s:105 +0xc
github.com/ipfs/go-bitswap/testnet.(*networkClient).SendMessage(0x8d4c400, 0x8730240, 0x8f497c0, 0x8d4e0d0, 0x7, 0x8734900, 0x8f49960, 0x0, 0xffffffff)
	/home/runner/go/pkg/mod/github.com/ipfs/go-bitswap@v0.3.3/testnet/virtual.go:216 +0x9c
github.com/ipfs/go-bitswap/testnet.(*messagePasser).SendMsg(0x8c16860, 0x8730240, 0x8f497c0, 0x8734900, 0x8f49960, 0x2, 0x0)
	/home/runner/go/pkg/mod/github.com/ipfs/go-bitswap@v0.3.3/testnet/virtual.go:260 +0x51
github.com/ipfs/go-bitswap/internal/messagequeue.(*MessageQueue).sendMessage(0x8cf83c0)
	/home/runner/go/pkg/mod/github.com/ipfs/go-bitswap@v0.3.3/internal/messagequeue/messagequeue.go:518 +0x247
github.com/ipfs/go-bitswap/internal/messagequeue.(*MessageQueue).sendIfReady(0x8cf83c0)
	/home/runner/go/pkg/mod/github.com/ipfs/go-bitswap@v0.3.3/internal/messagequeue/messagequeue.go:487 +0x39
github.com/ipfs/go-bitswap/internal/messagequeue.(*MessageQueue).runQueue(0x8cf83c0)
	/home/runner/go/pkg/mod/github.com/ipfs/go-bitswap@v0.3.3/internal/messagequeue/messagequeue.go:436 +0x3eb
created by github.com/ipfs/go-bitswap/internal/messagequeue.(*MessageQueue).Startup
	/home/runner/go/pkg/mod/github.com/ipfs/go-bitswap@v0.3.3/internal/messagequeue/messagequeue.go:374 +0x8c
FAIL	github.com/ipfs/go-fetcher/impl/blockservice	0.011s
?   	github.com/ipfs/go-fetcher/testutil	[no test files]
FAIL

**Comment by Jorropo** [comment]
Wdorks now AFAIT, please reopen if not.
